version: '3.8'

services:
  btex:
    build: .
    container_name: btex
    user: 1000:1000
    restart: unless-stopped
    volumes:
      # Mount torrent source directory (configurable via SRC_PATH)
      - ${SRC_PATH:-/src}:${SRC_PATH:-/src}
      # Mount TV destination directory (configurable via DEST_PATH)
      - ${DEST_PATH:-/srv}:${DEST_PATH:-/srv}
    volumes:
      # NOTE, btex looks under /src/finished
      - /where/your/torrents/live:/src
      - /where/your/torrents/go:/srv
    environment:
      - PYTHONUNBUFFERED=1
      # Email configuration (optional)
      - SMTP_HOST=${SMTP_HOST:-}
      - SMTP_USERNAME=${SMTP_USERNAME:-}
      - SMTP_PASSWORD=${SMTP_PASSWORD:-}
      - EMAIL_SENDER=${EMAIL_SENDER:-}
      - EMAIL_RECIPIENT=${EMAIL_RECIPIENT:-}
