name: Release Docker Image

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-push:
    permissions:
      contents: read
      packages: write
    uses: ./.github/workflows/docker-build-reusable.yml
    with:
      context: '.'
      platforms: 'linux/amd64,linux/arm64'
      push: true
      image-name: mfg81/btex
      registry: docker.io
      use-metadata: true
      login-required: true
    secrets:
      registry-username: ${{ secrets.DOCKERHUB_USERNAME }}
      registry-password: ${{ secrets.DOCKERHUB_TOKEN }}
